
[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[[colors.indexed_colors]]
color = "0xcb4b16"
index = 16

[[colors.indexed_colors]]
color = "0xd33682"
index = 17

[[colors.indexed_colors]]
color = "0xeee8d5"
index = 18

[[colors.indexed_colors]]
color = "0x93a1a1"
index = 19

[[colors.indexed_colors]]
color = "0x657b83"
index = 20

[[colors.indexed_colors]]
color = "0x073642"
index = 21

[colors.bright]
black = "0x839496"
blue = "0x268bd2"
cyan = "0x2aa198"
green = "0x859900"
magenta = "0x6c71c4"
red = "0xdc322f"
white = "0x002b36"
yellow = "0xb58900"

[colors.cursor]
cursor = "0x586e75"
text = "0xfdf6e3"

[colors.normal]
black = "0xfdf6e3"
blue = "0x268bd2"
cyan = "0x2aa198"
green = "0x859900"
magenta = "0x6c71c4"
red = "0xdc322f"
white = "0x586e75"
yellow = "0xb58900"

[colors.primary]
background = "0xfdf6e3"
foreground = "0x586e75"

[cursor]
style = "Block"
unfocused_hollow = false

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[font]
size = 14

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[keyboard]
bindings = [
{ key = "v", mods = "option", chars = "\u0016"},
{ key = "r", mods = "option", chars = "\u0012"},
{ key = "w", mods = "option", chars = "\u0017"},
{ key = "d", mods = "Option", chars = "\u0004"},
{ key = "c", mods = "option", chars = "\u0003"},
{ key = "a", mods = "option", chars = "\u0001"},
{ key = "e", mods = "option", chars = "\u0005"},
{ key = "a", mods = "super", chars = "\u001ba"},
{ key = "Key6", mods = "option", chars = "\u001e"},
{ key = "Key6", mods = "Control", chars = "\u001e"},
{ key = "Paste",                                                                        action = "Paste"          },
{ key = "Copy",                                                                         action = "Copy"           },
{ key = "L",        mods = "Control",                                                   action = "ClearLogNotice" },
{ key = "L",        mods = "Control",                           chars = "\f"                                      },
{ key = "Home",     mods = "Alt",                               chars = "\u001B[1;3H"                             },
{ key = "Home",                           mode = "AppCursor",   chars = "\u001BOH"                                },
{ key = "Home",                           mode = "~AppCursor",  chars = "\u001B[H"                                },
{ key = "End",      mods = "Alt",                               chars = "\u001B[1;3F"                             },
{ key = "End",                            mode = "AppCursor",   chars = "\u001BOF"                                },
{ key = "End",                            mode = "~AppCursor",  chars = "\u001B[F"                                },
{ key = "PageUp",   mods = "Shift",        mode = "~Alt",                                action = "ScrollPageUp"   },
{ key = "PageUp",   mods = "Shift",       mode = "Alt",         chars = "\u001B[5;2~"                             },
{ key = "PageUp",   mods = "Control",                           chars = "\u001B[5;5~"                             },
{ key = "PageUp",   mods = "Alt",                               chars = "\u001B[5;3~" },
{ key = "PageUp",                                               chars = "\u001B[5~" },
{ key = "PageDown", mods = "Shift",       mode = "~Alt",                                action = "ScrollPageDown" },
{ key = "PageDown", mods = "Shift",       mode = "Alt",         chars = "\u001B[6;2~" },
{ key = "PageDown", mods = "Control",                           chars = "\u001B[6;5~" },
{ key = "PageDown", mods = "Alt",                               chars = "\u001B[6;3~" },
{ key = "PageDown",                                             chars = "\u001B[6~" },
{ key = "Tab", mods = "Shift", chars = "\u001B[Z" },
{ key = "Back", chars = "\u007F" },
{ key = "Back", mods = "Alt", chars = "\u001B\u007F"},
{ key = "Insert", chars = "\u001B[2~"},
{ key = "Delete", chars = "\u001B[3~"},
{ key = "Left", chars = "\u001B[1;2D", mods = "Shift"},
{ key = "Left", chars = "\u001B[1;5D", mods = "Control"},
{ key = "Left", chars = "\u001B[1;3D", mods = "Alt"},
{ key = "Left", chars = "\u001B[D", mode = "~AppCursor"},
{ key = "Left", chars = "\u001BOD", mode = "AppCursor"},
{ key = "Right", chars = "\u001B[1;2C", mods = "Shift"},
{ key = "Right", chars = "\u001B[1;5C", mods = "Control"},
{ key = "Right", chars = "\u001B[1;3C", mods = "Alt"},
{ key = "Right", chars = "\u001B[C", mode = "~AppCursor"},
{ key = "Right", chars = "\u001BOC", mode = "AppCursor"},
{ key = "Up", chars = "\u001B[1;2A", mods = "Shift"},
{ key = "Up", chars = "\u001B[1;5A", mods = "Control"},
{ key = "Up", chars = "\u001B[1;3A", mods = "Alt"},
{ key = "Up", chars = "\u001B[A", mode = "~AppCursor"},
{ key = "Up", chars = "\u001BOA", mode = "AppCursor" },
{ key = "Down", chars = "\u001B[1;2B", mods = "Shift"},
{ key = "Down", chars = "\u001B[1;5B", mods = "Control"},
{ key = "Down", chars = "\u001B[1;3B", mods = "Alt"},
{ key = "Down", chars = "\u001B[B", mode = "~AppCursor"},
{ key = "Down", chars = "\u001BOB", mode = "AppCursor"},
{ key = "F1", chars = "\u001BOP"},
{ key = "F2", chars = "\u001BOQ"},
{ key = "F3", chars = "\u001BOR"},
{ key = "F4", chars = "\u001BOS"},
{ key = "F5", chars = "\u001B[15~" },
{ key = "F6", chars = "\u001B[17~" },
{ key = "F7", chars = "\u001B[18~" },
{ key = "F8", chars = "\u001B[19~" },
{ key = "F9", chars = "\u001B[20~" },
{ chars = "\u001B[21~", key = "F10"},
{ chars = "\u001B[23~", key = "F11"},
{ chars = "\u001B[24~", key = "F12"},
{ chars = "\u001B[1;2P", key = "F1", mods = "Shift"},
{ chars = "\u001B[1;2Q", key = "F2", mods = "Shift" },
{ chars = "\u001B[1;2R", key = "F3", mods = "Shift" },
{ chars = "\u001B[1;2S", key = "F4", mods = "Shift" },
{ chars = "\u001B[15;2~", key = "F5", mods = "Shift" },
{ chars = "\u001B[17;2~", key = "F6", mods = "Shift" },
{ chars = "\u001B[18;2~", key = "F7", mods = "Shift" },
{ chars = "\u001B[19;2~", key = "F8", mods = "Shift" },
{ chars = "\u001B[20;2~", key = "F9", mods = "Shift" },
{ chars = "\u001B[21;2~", key = "F10", mods = "Shift" },
{ chars = "\u001B[23;2~", key = "F11", mods = "Shift" },
{ chars = "\u001B[24;2~", key = "F12", mods = "Shift" },
{ chars = "\u001B[1;5P", key = "F1", mods = "Control" },
{ chars = "\u001B[1;5Q", key = "F2", mods = "Control" },
{ chars = "\u001B[1;5R", key = "F3", mods = "Control" },
{ chars = "\u001B[1;5S", key = "F4", mods = "Control" },
{ chars = "\u001B[15;5~", key = "F5", mods = "Control" },
{ chars = "\u001B[17;5~", key = "F6", mods = "Control" },
{ chars = "\u001B[18;5~", key = "F7", mods = "Control" },
{ chars = "\u001B[19;5~", key = "F8", mods = "Control" },
{ chars = "\u001B[20;5~", key = "F9", mods = "Control" },
{ chars = "\u001B[21;5~", key = "F10", mods = "Control" },
{ chars = "\u001B[23;5~", key = "F11", mods = "Control" },
{ chars = "\u001B[24;5~", key = "F12", mods = "Control" },
{ chars = "\u001B[1;6P", key = "F1", mods = "Alt" },
{ chars = "\u001B[1;6Q", key = "F2", mods = "Alt" },
{ chars = "\u001B[1;6R", key = "F3", mods = "Alt" },
{ chars = "\u001B[1;6S", key = "F4", mods = "Alt" },
{ chars = "\u001B[15;6~", key = "F5", mods = "Alt" },
{ chars = "\u001B[17;6~", key = "F6", mods = "Alt" },
{ chars = "\u001B[18;6~", key = "F7", mods = "Alt" },
{ chars = "\u001B[19;6~", key = "F8", mods = "Alt" },
{ chars = "\u001B[20;6~", key = "F9", mods = "Alt" },
{ chars = "\u001B[21;6~", key = "F10", mods = "Alt" },
{ chars = "\u001B[23;6~", key = "F11", mods = "Alt" },
{ chars = "\u001B[24;6~", key = "F12", mods = "Alt" },
{ chars = "\u001B[1;3P", key = "F1", mods = "Super" },
{ chars = "\u001B[1;3Q", key = "F2", mods = "Super" },
{ chars = "\u001B[1;3R", key = "F3", mods = "Super" },
{ chars = "\u001B[1;3S", key = "F4", mods = "Super" },
{ chars = "\u001B[15;3~", key = "F5", mods = "Super" },
{ chars = "\u001B[17;3~", key = "F6", mods = "Super" },
{ chars = "\u001B[18;3~", key = "F7", mods = "Super" },
{ chars = "\u001B[19;3~", key = "F8", mods = "Super" },
{ chars = "\u001B[20;3~", key = "F9", mods = "Super" },
{ chars = "\u001B[21;3~", key = "F10", mods = "Super" },
{ chars = "\u001B[23;3~", key = "F11", mods = "Super" },
{ chars = "\u001B[24;3~", key = "F12", mods = "Super" },
{ chars = """, """, key = "NumpadEnter" }
]


[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>"

[window]
decorations = "full"
dynamic_padding = false
dynamic_title = true
startup_mode = "Windowed"
option_as_alt = "OnlyRight"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0

[general]
live_config_reload = true
working_directory = "None"
